### ISSUE TITLE
About diffraction effect

### ISSUE THREAD

**Issue by OscarLiau** [GAMMA-UMD/pygsound#6]
Hi RoyJames,

Thanks for your work and it works perfect! But I had one question, in the paper "**GSOUND: INTERACTIVE SOUND PROPAGATION FOR GAMES**" by C. Schiller, D. Manocha, diffraction of sound is considered instead of diffusion reflection, and it seems otherwise for **pygsound**. 

Is these two the same algorithm, or the python version is actually different from the paper **GSOUND**? 
Thanks!

**Comment by RoyJames** [comment]
Thank you for your interest! There are some variations of GSound made by our group including the diffraction version that Carl has worked on. However, most of those features were not stable or efficient enough to be integrated as a release package. Therefore, the pygsound package here only contains the most stable/basic components of GSound based on which we build new algorithms. I hope this clarifies some questions.

**Comment by OscarLiau** [comment]
Got it, thanks Roy!
